---

- name: Habilitar e iniciar firewall
  service: name=firewalld state=started enabled=yes
- name: set modprobe
  shell: modprobe br_netfilter
- name: Activar transparent masquerading
  firewalld: masquerade=yes permanent=true state=enabled
  #notify: reload firewalld
- name: Reiniciar firewall
  command: firewall-cmd --reload
- name: Permitir a Kubernetes manejar el trafico
  blockinfile:
    path: "/etc/sysctl.d/k8s.conf"
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
- name: Aplicando cambios de configuracion
  command: sysctl --system
#- name: Deshabilitar swap (comenta la linea)
#  shell: |
#         swapoff -a
#         sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
- name: Deshabilitar swap
  shell: |
         swapoff -a
         sed -i '/swap/d' /etc/fstab

- name: Agregar repo de docker
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Instalar docker
  yum:
    name: docker-ce
    state: latest

- name: Iniciar servicio docker
  service:
    name: docker
    state: started
    enabled: yes

#- name: Agregar repo de kubernetes
#  yum_repository:
#      name: "K8s-repo"
#      description: "Repository for K8s"
#      baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
#      gpgcheck: no
- name: Agregar repo de kubernetes
  blockinfile:
     create: yes
     path: "/etc/yum.repos.d/kubernetes.repo"
     block: |
            [kubernetes]
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            exclude=kubelet kubeadm kubectl

#- name: Instalar kubeadm, kubectl y kubelet
#  package:
#      name: "kubeadm"
#      state: present
#      disable_excludes: kubernetes

- name: Instalar kubeadm, kubectl y kubelet
  command: 
    cmd: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    warn: no
- name: Iniciando y habilitando servicio kubelet permanentemente
  service:
      name: "kubelet"
      state: started
      enabled: yes

